### PR TITLE
Nfultz/foreach to future

### PR DESCRIPTION
**Pull request by nfultz**
Replacing foreach dependencies with future, which seems to work somewhat better on windows - at the minimum, it no longer errors depending on package load ordering, and no longer has serialization warnings. 

This also let us get rid of much of the foreach scaffolding.

side note - collapsed bootstrap/bootstrap_sims arguments into one parameter.

### CODE REVIEW

**Comment by graemeblair** [comment]
LGTM, I think the PR error is an estimatr prob?

**Comment by nfultz** [comment]
Mac oldrel failed, I'm just going to restart it and see if it fixes it.

**Comment by graemeblair** [comment]
could this bc mac-oldrel binary doesn't exist on CRAN for future.apply? shouldn't it compile from source if that's the case to install?

**Comment by nfultz** [comment]
Also closes #64

**Comment by graemeblair** [comment]
LGTM

**Pull request merged**
