### PR TITLE
diagnosis fixes

### PR DESCRIPTION
**Pull request by graemeblair**
Addresses sorting and some other issues from https://github.com/DeclareDesign/DeclareDesign/issues/204

### CODE REVIEW

**Review by acoppock — APPROVED** [review]
omg ltgm

**Comment by nfultz** [comment]
Are you approving yourself?

**Comment by graemeblair** [comment]
Hi @nfultz, Alex and I are working together so names may be confused, but are both checking each PR. Feel free to comment on any of them.

**Comment by nfultz** [comment]
You can merge without approvals in that case, you should have admin access.

**Pull request merged**
