### PR TITLE
bug fix for expand_design for handling functions etc.

### LINKED ISSUE #224: expand_design very odd behavior
looks broke. This is using most recent version of all packages and example from documentation, but just adding a param:

```r
library(DeclareDesign)
template <- function(N,ate) {
  pop <- declare_population(N = N, noise = rnorm(N))
  pos <- declare_potential_outcomes(Y ~ ate * Z + noise)
  assgn <- declare_assignment(m = N / 2)
  mand <- declare_estimand(ATE = mean(Y_Z_1 - Y_Z_0))
  mator <- declare_estimator(Y ~ Z, estimand = mand)
  pop + pos + assgn + mand + mator
}
designs <- expand_design(template, N = seq(30, 100, 10),ate = seq(0,.5,length.out = 10))
sapply(designs,attr,"parameters")
```
produces:
```
    design_1 design_2 design_3 design_4 design_5 design_6 design_7 design_8 design_9
N   "30"     "100"    "10"     "30"     "100"    "10"     "30"     "100"    "10"    
ate "0"      "0"      "0"      "0.5"    "0.5"    "0.5"    "10"     "10"     "10"    
    design_10 design_11 design_12 design_13 design_14 design_15 design_16 design_17
N   "NA"      "NA"      "NA"      "NA"      "NA"      "NA"      "NA"      "NA"     
ate "NA"      "NA"      "NA"      "NA"      "NA"      "NA"      "NA"      "NA"     
 .... (etc)
```

### PR DESCRIPTION
**Pull request by graemeblair**
closes #224

### CODE REVIEW

**Comment by nfultz** [comment]
This does not work when I tested it.

**Comment by graemeblair** [comment]
uf, thanks. will take a look.

**Comment by graemeblair** [comment]
I think this is good to go see https://github.com/DeclareDesign/DeclareDesign/issues/224#issuecomment-399209660

**Review by acoppock — APPROVED** [review]
lgtm

**Pull request merged**
