### PR TITLE
Nfultz/next

### PR DESCRIPTION
**Pull request by nfultz**

### CODE REVIEW

**Review by graemeblair — COMMENTED** [review]
looks great! 

couldn't understand: what is restore()?

**Comment by nfultz** [comment]
restore replaces Z if it was overwritten by fabricate.

**Comment by graemeblair** [comment]
thanks. what's the scenario where `fabricate` overwrites it?

**Comment by nfultz** [comment]
when it's already present. See also alex's ticket about thqt.

**Comment by graemeblair** [comment]
thanks

**Review by graemeblair — APPROVED** [review]
LGTM. read the code and understand the restore() solution now. there's a lot of changes here, so suggest we merge when you're ready Neal and then play around with more

**Review by graemeblair — COMMENTED** [review]
Typo here:
data.frame(coefficient = rownames(summ),

should be coefficients I think

**Comment by nfultz** [comment]
We usually do singular on columns eg estimate

**Pull request merged**
